/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RelacionamentosRouteImport } from './routes/relacionamentos'
import { Route as PsicoterapiaOnlineRouteImport } from './routes/psicoterapia-online'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DepressaoRouteImport } from './routes/depressao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AutoconhecimentoRouteImport } from './routes/autoconhecimento'
import { Route as AnsiedadeRouteImport } from './routes/ansiedade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as KeystaticSplatRouteImport } from './routes/keystatic/$'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiKeystaticSplatRouteImport } from './routes/api/keystatic.$'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RelacionamentosRoute = RelacionamentosRouteImport.update({
  id: '/relacionamentos',
  path: '/relacionamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicoterapiaOnlineRoute = PsicoterapiaOnlineRouteImport.update({
  id: '/psicoterapia-online',
  path: '/psicoterapia-online',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DepressaoRoute = DepressaoRouteImport.update({
  id: '/depressao',
  path: '/depressao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoconhecimentoRoute = AutoconhecimentoRouteImport.update({
  id: '/autoconhecimento',
  path: '/autoconhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsiedadeRoute = AnsiedadeRouteImport.update({
  id: '/ansiedade',
  path: '/ansiedade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeystaticSplatRoute = KeystaticSplatRouteImport.update({
  id: '/keystatic/$',
  path: '/keystatic/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeystaticSplatRoute = ApiKeystaticSplatRouteImport.update({
  id: '/api/keystatic/$',
  path: '/api/keystatic/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ansiedade': typeof AnsiedadeRoute
  '/autoconhecimento': typeof AutoconhecimentoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/depressao': typeof DepressaoRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/psicoterapia-online': typeof PsicoterapiaOnlineRoute
  '/relacionamentos': typeof RelacionamentosRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ansiedade': typeof AnsiedadeRoute
  '/autoconhecimento': typeof AutoconhecimentoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/depressao': typeof DepressaoRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/psicoterapia-online': typeof PsicoterapiaOnlineRoute
  '/relacionamentos': typeof RelacionamentosRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/blog': typeof BlogIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ansiedade': typeof AnsiedadeRoute
  '/autoconhecimento': typeof AutoconhecimentoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/depressao': typeof DepressaoRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/psicoterapia-online': typeof PsicoterapiaOnlineRoute
  '/relacionamentos': typeof RelacionamentosRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/keystatic/$': typeof KeystaticSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/api/keystatic/$': typeof ApiKeystaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ansiedade'
    | '/autoconhecimento'
    | '/como-funciona'
    | '/contato'
    | '/depressao'
    | '/faq'
    | '/privacidade'
    | '/psicoterapia-online'
    | '/relacionamentos'
    | '/sobre'
    | '/blog/$slug'
    | '/keystatic/$'
    | '/blog/'
    | '/api/keystatic/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ansiedade'
    | '/autoconhecimento'
    | '/como-funciona'
    | '/contato'
    | '/depressao'
    | '/faq'
    | '/privacidade'
    | '/psicoterapia-online'
    | '/relacionamentos'
    | '/sobre'
    | '/blog/$slug'
    | '/keystatic/$'
    | '/blog'
    | '/api/keystatic/$'
  id:
    | '__root__'
    | '/'
    | '/ansiedade'
    | '/autoconhecimento'
    | '/como-funciona'
    | '/contato'
    | '/depressao'
    | '/faq'
    | '/privacidade'
    | '/psicoterapia-online'
    | '/relacionamentos'
    | '/sobre'
    | '/blog/$slug'
    | '/keystatic/$'
    | '/blog/'
    | '/api/keystatic/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnsiedadeRoute: typeof AnsiedadeRoute
  AutoconhecimentoRoute: typeof AutoconhecimentoRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  DepressaoRoute: typeof DepressaoRoute
  FaqRoute: typeof FaqRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PsicoterapiaOnlineRoute: typeof PsicoterapiaOnlineRoute
  RelacionamentosRoute: typeof RelacionamentosRoute
  SobreRoute: typeof SobreRoute
  BlogSlugRoute: typeof BlogSlugRoute
  KeystaticSplatRoute: typeof KeystaticSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiKeystaticSplatRoute: typeof ApiKeystaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relacionamentos': {
      id: '/relacionamentos'
      path: '/relacionamentos'
      fullPath: '/relacionamentos'
      preLoaderRoute: typeof RelacionamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicoterapia-online': {
      id: '/psicoterapia-online'
      path: '/psicoterapia-online'
      fullPath: '/psicoterapia-online'
      preLoaderRoute: typeof PsicoterapiaOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depressao': {
      id: '/depressao'
      path: '/depressao'
      fullPath: '/depressao'
      preLoaderRoute: typeof DepressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoconhecimento': {
      id: '/autoconhecimento'
      path: '/autoconhecimento'
      fullPath: '/autoconhecimento'
      preLoaderRoute: typeof AutoconhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ansiedade': {
      id: '/ansiedade'
      path: '/ansiedade'
      fullPath: '/ansiedade'
      preLoaderRoute: typeof AnsiedadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keystatic/$': {
      id: '/keystatic/$'
      path: '/keystatic/$'
      fullPath: '/keystatic/$'
      preLoaderRoute: typeof KeystaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keystatic/$': {
      id: '/api/keystatic/$'
      path: '/api/keystatic/$'
      fullPath: '/api/keystatic/$'
      preLoaderRoute: typeof ApiKeystaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnsiedadeRoute: AnsiedadeRoute,
  AutoconhecimentoRoute: AutoconhecimentoRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  DepressaoRoute: DepressaoRoute,
  FaqRoute: FaqRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PsicoterapiaOnlineRoute: PsicoterapiaOnlineRoute,
  RelacionamentosRoute: RelacionamentosRoute,
  SobreRoute: SobreRoute,
  BlogSlugRoute: BlogSlugRoute,
  KeystaticSplatRoute: KeystaticSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiKeystaticSplatRoute: ApiKeystaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
